@startuml

actor Caller as C
participant DefaultForecastRepository as R
database CityForecastDB as DB
participant cityForecastedMapper as M

C -> R : GetForecastForCity(cityName:string, date:string)
activate R
    R -> DB : SELECT * FROM {cityTableName} JOIN {forecastTableName}\n WHERE city.Name = **cityName**\n AND forecast.Date = **date**
    note top: implement using gorm
    R <-- DB : (cityContract:contracts.CityForecasted, dbError:error)
    break dbError != nil
        R --> C : contracts.CityForecasted{}, errors.Wrapf(dbError,\n "error getting city with name '%s' and date '%s'", cityName, date)
    end
    alt resultRows == 0
        R --> C : contracts.CityForecasted{}, nil:error
    end
    R -> M : ToCityForecastedEntity(cityContract)
    activate M
        R <-- M : cityForecastedModel:entities.CityForecasted
    deactivate
    R --> C : cityForecastedModel, nil:error
deactivate

@enduml
