@startuml

actor Caller as C
participant defaultRestMusementClient as RC
participant musementAPI as A

C -> RC ++: GetCitiesRequest()
    RC -> RC: baseURL := this.config.BaseURL()\

    RC -> A ++:curl --request GET \\ \
                 \n   --url **{baseURL}**/cities \\ \
                 \n   --header 'X-Musement-Application: {applicationValue}' \\ \
                 \n   --header 'X-Musement-Version: 3.4.0' \\ \
                 \n   --header 'Authorization: Bearer **{this.config.MusementClientToken()}**'
    return response:models.MusementAPIResponse, reqErr:error
return response, reqErr
@enduml
