// Code generated by mockery v2.14.0. DO NOT EDIT.

package musement

import (
	mock "github.com/stretchr/testify/mock"

	response "musement/src/internal/infrastructure/providers/musement/internal/response"
)

// MockRestMusementClient is an autogenerated mock type for the restMusementClient type
type MockRestMusementClient struct {
	mock.Mock
}

// GetCitiesRequest provides a mock function with given fields:
func (_m *MockRestMusementClient) GetCitiesRequest() (response.MusementAPIResponse, error) {
	ret := _m.Called()

	var r0 response.MusementAPIResponse
	if rf, ok := ret.Get(0).(func() response.MusementAPIResponse); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(response.MusementAPIResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockRestMusementClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRestMusementClient creates a new instance of MockRestMusementClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRestMusementClient(t mockConstructorTestingTNewMockRestMusementClient) *MockRestMusementClient {
	mock := &MockRestMusementClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
