// Code generated by mockery v2.14.0. DO NOT EDIT.

package client

import (
	config "musement/src/internal/infrastructure/providers/weather/config"

	mock "github.com/stretchr/testify/mock"
)

// MockConfig is an autogenerated mock type for the Config type
type MockConfig struct {
	mock.Mock
}

// WeatherProviderClientConfig provides a mock function with given fields:
func (_m *MockConfig) WeatherProviderClientConfig() config.WeatherProviderClientConfig {
	ret := _m.Called()

	var r0 config.WeatherProviderClientConfig
	if rf, ok := ret.Get(0).(func() config.WeatherProviderClientConfig); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(config.WeatherProviderClientConfig)
	}

	return r0
}

type mockConstructorTestingTNewMockConfig interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockConfig creates a new instance of MockConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockConfig(t mockConstructorTestingTNewMockConfig) *MockConfig {
	mock := &MockConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
