@startuml

package "src.models"{
    class CityForecasted {
        + Name:string
        + Forecasts:[]Forecast
    }

    class Forecast {
        + Order:int
        + Description:string
    }
}

CityForecasted o-- Forecast

@enduml
