// Code generated by mockery v2.14.0. DO NOT EDIT.

package client

import mock "github.com/stretchr/testify/mock"

// MockConfig is an autogenerated mock type for the WeatherProviderClientConfig type
type MockConfig struct {
	mock.Mock
}

// BaseURL provides a mock function with given fields:
func (_m *MockConfig) BaseURL() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ForecastDays provides a mock function with given fields:
func (_m *MockConfig) ForecastDays() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// WeatherClientToken provides a mock function with given fields:
func (_m *MockConfig) WeatherClientToken() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewMockConfig interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockConfig creates a new instance of MockConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockConfig(t mockConstructorTestingTNewMockConfig) *MockConfig {
	mock := &MockConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
