// Code generated by mockery v2.14.0. DO NOT EDIT.

package weather

import (
	response "musement/src/internal/infrastructure/providers/weather/internal/response"

	mock "github.com/stretchr/testify/mock"
)

// MockRestWeatherClient is an autogenerated mock type for the restWeatherClient type
type MockRestWeatherClient struct {
	mock.Mock
}

// GetForecastForCityRequest provides a mock function with given fields: cityLat, cityLong
func (_m *MockRestWeatherClient) GetForecastForCityRequest(cityLat float64, cityLong float64) (response.WeatherAPIResponse, error) {
	ret := _m.Called(cityLat, cityLong)

	var r0 response.WeatherAPIResponse
	if rf, ok := ret.Get(0).(func(float64, float64) response.WeatherAPIResponse); ok {
		r0 = rf(cityLat, cityLong)
	} else {
		r0 = ret.Get(0).(response.WeatherAPIResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(float64, float64) error); ok {
		r1 = rf(cityLat, cityLong)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockRestWeatherClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRestWeatherClient creates a new instance of MockRestWeatherClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRestWeatherClient(t mockConstructorTestingTNewMockRestWeatherClient) *MockRestWeatherClient {
	mock := &MockRestWeatherClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
