// Code generated by mockery v2.14.0. DO NOT EDIT.

package weather

import mock "github.com/stretchr/testify/mock"

// MockWeatherProviderClientConfig is an autogenerated mock type for the WeatherProviderClientConfig type
type MockWeatherProviderClientConfig struct {
	mock.Mock
}

// BaseURL provides a mock function with given fields:
func (_m *MockWeatherProviderClientConfig) BaseURL() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ForecastDays provides a mock function with given fields:
func (_m *MockWeatherProviderClientConfig) ForecastDays() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// WeatherClientToken provides a mock function with given fields:
func (_m *MockWeatherProviderClientConfig) WeatherClientToken() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewMockWeatherProviderClientConfig interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockWeatherProviderClientConfig creates a new instance of MockWeatherProviderClientConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockWeatherProviderClientConfig(t mockConstructorTestingTNewMockWeatherProviderClientConfig) *MockWeatherProviderClientConfig {
	mock := &MockWeatherProviderClientConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
