// Code generated by mockery v2.14.0. DO NOT EDIT.

package getforecast

import mock "github.com/stretchr/testify/mock"

// MockResponsePrinter is an autogenerated mock type for the responsePrinter type
type MockResponsePrinter struct {
	mock.Mock
}

// PrintCity provides a mock function with given fields: cityFormatted
func (_m *MockResponsePrinter) PrintCity(cityFormatted string) {
	_m.Called(cityFormatted)
}

type mockConstructorTestingTNewMockResponsePrinter interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockResponsePrinter creates a new instance of MockResponsePrinter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockResponsePrinter(t mockConstructorTestingTNewMockResponsePrinter) *MockResponsePrinter {
	mock := &MockResponsePrinter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
